### ISSUE TITLE
Please explain plugin usefulness

### ISSUE THREAD

**Issue by pcav** [icsm-au/icsm_qgis_transformer#3]
It seems to replicate functionality already present in http://plugins.qgis.org/plugins/ntv2_transformations/
If so, it would make more sense to merge your work there.
Sorry for bothering, but we are trying hard to reduce duplication, as it causes confusion for the users, and more load on infrastructure management. Think if every country would do the same for their national grids.
Thanks.

**Comment by alexgleith** [comment]
Hi @pcav 

We've implemented the Australian transformation in the NaturalGIS plugin already.

This plugin is required because we are hoping to make it as simple as possible to undertake the Australian transformations. Even simpler than the NaturalGIS plugin.

We also have efforts in place to get our transformation grids into the upstream project, so that this plugin is made redundant.

**Comment by pcav** [comment]
I understand. Please make the plugin deprecated when it will be redundant.
